packages:
  - apps/dashboard.regarde.dev
  - apps/regarde.bio/*
  - packages/*

catalog:
  "@clerk/clerk-react": ^5.61.3
  "@hono/node-server": ^1.19.11
  "@hono/swagger-ui": ^0.5.3
  "@hono/zod-openapi": ^1.2.2
  "@scure/bip39": ^2.0.1
  "@types/node": ^25.5.0
  "@types/react": ~19.2.14
  "@types/react-dom": ^19.2.3
  "@vitest/ui": ^4.1.0
  cojson: ^0.20.14
  cojson-core-rn: ^0.20.14
  cojson-transport-ws: ^0.20.14
  dotenv: ^17.3.1
  hono: ^4.12.7
  jazz-tools: ^0.20.14
  little-timestamp: ^1.0.0
  react: 19.2.4
  react-dom: 19.2.4
  typescript: ^5.9.3
  ulidx: ^2.4.1
  vite: 8.0.0-beta.5
  vite-plugin-dts: ^4.5.4
  vite-tsconfig-paths: ^6.1.1
  vitest: ^4.1.0
  zod: ^4.3.6

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@clerk/shared"
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - better-sqlite3
  - esbuild
