packages:
  - app/regarde.bio/*
  - packages/*

catalog:
  '@clerk/clerk-react': ^5.59.3
  '@hono/node-server': ^1.19.8
  '@hono/swagger-ui': ^0.5.3
  '@hono/zod-openapi': ^1.2.0
  '@scure/bip39': ^2.0.1
  '@types/node': ^25.0.6
  '@types/react': ~19.2.8
  '@types/react-dom': ^19.2.3
  '@vitest/ui': ^4.0.16
  cojson-core-rn: ^0.19.19
  cojson-transport-ws: ^0.19.19
  dotenv: ^17.2.3
  hono: ^4.11.3
  jazz-tools: ^0.19.19
  preact: ^10.28.2
  prettier: ^3.7.4
  react: 19.1.1
  react-dom: 19.1.1
  typescript: ^5.9.3
  ulidx: ^2.4.1
  vite: 8.0.0-beta.5
  vite-plugin-dts: ^4.5.4
  vite-tsconfig-paths: ^6.0.4
  vitest: ^4.0.16
  zod: 4.1.11

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@clerk/shared'
  - '@tailwindcss/oxide'
  - esbuild
