packages:
  - apps/dashboard.regarde.dev/*
  - apps/regarde.bio/*
  - packages/*

catalog:
  "@clerk/clerk-react": ^5.60.0
  "@hono/node-server": ^1.19.9
  "@hono/swagger-ui": ^0.5.3
  "@hono/zod-openapi": ^1.2.1
  "@scure/bip39": ^2.0.1
  "@types/node": ^25.2.0
  "@types/react": ~19.2.10
  "@types/react-dom": ^19.2.3
  "@vitest/ui": ^4.0.18
  cojson-core-rn: ^0.20.7
  cojson-transport-ws: ^0.20.7
  dotenv: ^17.2.3
  hono: ^4.11.7
  jazz-tools: ^0.20.7
  preact: ^10.28.3
  react: 19.1.1
  react-dom: 19.1.1
  typescript: ^5.9.3
  ulidx: ^2.4.1
  vite: 8.0.0-beta.5
  vite-plugin-dts: ^4.5.4
  vite-tsconfig-paths: ^6.0.5
  vitest: ^4.0.18
  zod: ^4.3.6

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@clerk/shared"
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - better-sqlite3
  - esbuild
