import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Landing page specific colors
        landing: {
          background: 'var(--color-landing-background)',
          foreground: 'var(--color-landing-foreground)',
          border: 'var(--color-landing-border)',
          'header-bg': 'var(--color-landing-header-bg)',
          'header-text': 'var(--color-landing-header-text)',
          'button-text': 'var(--color-landing-button-text)',
        },
      },
    },
    fontFamily: {
      sans: 'var(--font-sans)',
      mono: 'var(--font-mono)',
      serif: 'var(--font-serif)',
    },
    fontSize: {
      xs: 'var(--font-size-xs)',
      sm: 'var(--font-size-sm)',
      md: 'var(--font-size-md)',
      lg: 'var(--font-size-lg)',
      xl: 'var(--font-size-xl)',
    },
    borderRadius: {
      DEFAULT: 'var(--radius)',
      sm: 'var(--radius-sm)',
      md: 'var(--radius-md)',
      lg: 'var(--radius-lg)',
      xl: 'var(--radius-xl)',
    },
    colors: {
      background: 'var(--color-background)',
      foreground: 'var(--color-foreground)',
      card: 'var(--color-card)',
      'card-foreground': 'var(--color-card-foreground)',
      popover: 'var(--color-popover)',
      'popover-foreground': 'var(--color-popover-foreground)',
      primary: 'var(--color-primary)',
      'primary-foreground': 'var(--color-primary-foreground)',
      secondary: 'var(--color-secondary)',
      'secondary-foreground': 'var(--color-secondary-foreground)',
      muted: 'var(--color-muted)',
      'muted-foreground': 'var(--color-muted-foreground)',
      accent: 'var(--color-accent)',
      'accent-foreground': 'var(--color-accent-foreground)',
      destructive: 'var(--color-destructive)',
      'destructive-foreground': 'var(--color-destructive-foreground)',
      border: 'var(--color-border)',
      input: 'var(--color-input)',
      ring: 'var(--color-ring)',
      chart: {
        1: 'var(--color-chart-1)',
        2: 'var(--color-chart-2)',
        3: 'var(--color-chart-3)',
        4: 'var(--color-chart-4)',
        5: 'var(--color-chart-5)',
      },
      sidebar: 'var(--color-sidebar)',
      'sidebar-foreground': 'var(--color-sidebar-foreground)',
      'sidebar-primary': 'var(--color-sidebar-primary)',
      'sidebar-primary-foreground': 'var(--color-sidebar-primary-foreground)',
      'sidebar-accent': 'var(--color-sidebar-accent)',
      'sidebar-accent-foreground': 'var(--color-sidebar-accent-foreground)',
      'sidebar-border': 'var(--color-sidebar-border)',
      'sidebar-ring': 'var(--color-sidebar-ring)',
    },
    letterSpacing: {
      tighter: 'var(--tracking-tighter)',
      tight: 'var(--tracking-tight)',
      normal: 'var(--tracking-normal)',
      wide: 'var(--tracking-wide)',
      wider: 'var(--tracking-wider)',
      widest: 'var(--tracking-widest)',
    },
    boxShadow: {
      '2xs': 'var(--shadow-2xs)',
      xs: 'var(--shadow-xs)',
      sm: 'var(--shadow-sm)',
      DEFAULT: 'var(--shadow)',
      md: 'var(--shadow-md)',
      lg: 'var(--shadow-lg)',
      xl: 'var(--shadow-xl)',
      '2xl': 'var(--shadow-2xl)',
    },
  },
  plugins: [],
} satisfies Config;
